version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3333:3000'
  api:
    build: ./api
    ports:
      - '5555:5000'
  mysql: 
    image: mysql
    # Доступа к бд снаружи не будет
  adminer: 
    image: adminer
    ports:
      - '8888:8080'